### ISSUE TITLE
Warning under DMCA

### ISSUE THREAD

**Issue by kyranet** [tamejs/async-queue#6]
I just got word of this repository's existence, which is a copy-paste of [async-queue](https://github.com/sapphiredev/utilities/tree/main/packages/async-queue) with slightly different names but still nearly-identical logic. The offending code can be seen below:

https://github.com/tamejs/async-queue/blob/74b777dd007d9b9e3f3b1076c4eeaf3827dc8b20/src/index.ts#L1-L72

Which is identical to the [original source code](https://github.com/sapphiredev/utilities/blob/6644d949d3938a1bed3a456849ffe8c6f436038d/packages/async-queue/src/lib/AsyncQueue.ts#L1-L68).

And if it was not enough, this repository also re-licenses our work from MIT to Apache-2.0:

https://github.com/tamejs/async-queue/blob/74b777dd007d9b9e3f3b1076c4eeaf3827dc8b20/package.json#L8

Furthermore, this repository does not comply with the LICENSE requirements from `sapphiredev/utilities`, which `async-queue` inherits due to being part of it. This license in question is **The MIT License**, and can be seen [here](https://github.com/sapphiredev/utilities/blob/main/LICENSE.md).

Under the MIT license, you have some conditions for the re-distribution of the work, which is to keep the **license and copyright notice**. However, none can be seen in this repository as of 74b777dd007d9b9e3f3b1076c4eeaf3827dc8b20, which is the last commit made to the moment of writing this issue.

You may resolve this issue by pasting a full copy of our aforementioned license within the next 7 days.

---

On a personal note, you can just install `@sapphire/async-queue` from npmjs or yarnpkg, there is absolutely no need to republish and discredit us by claiming our code as yours with just "ideas taken from".

**Comment by AngeloCore** [comment]
Sorry, we fixed the mistake [here](https://github.com/tamejs/async-queue/commit/135fd5fb8181cbead9bb3f90969c117ccc59539f), please check that everything is as it should be, so that we can publish the new version officially.
<br />

> On a personal note, you can just install @sapphire/async-queue from npmjs or yarnpkg, there is absolutely no need to republish and discredit us by claiming our code as yours with just "ideas taken from".

Our library is currently under development, we initially used your package, but we decided to make a copy, so that we could change it as we wish in the future.

**Comment by kyranet** [comment]
Thank you for the rapid response, I just noticed a couple more things.

I forgot to include that a copyright notice must be added as well (although it was mentioned in the conditions anyways), in the last paragraph. Something like this in the offending file should be enough:
```javascript
// MIT License | Copyright © `2020` `The Sapphire Community and its contributors`
```

Also, I was pointed out to this line from your CODEOWNERS, I didn't even see it:

https://github.com/tamejs/async-queue/blob/74b777dd007d9b9e3f3b1076c4eeaf3827dc8b20/.github/CODEOWNERS#L1

---

> but we decided to make a copy, so that we could change it as we wish in the future.

Couldn't you just fork the source repository and create a Pull Request adding anything you may need? Creating clones of the same software creates fragmentation in the ecosystem, which is not really a good thing. One upside of this is that you will offload development costs to us and we will also provide tools such as our CI workflows and our test suite, which aid in the creation of stable, robust, and tested software.

**Comment by AngeloCore** [comment]
Hello there, done!

> Couldn't you just fork the source repository and create a Pull Request adding anything you may need? Creating clones of the same software creates fragmentation in the ecosystem, which is not really a good thing. One upside of this is that you will offload development costs to us and we will also provide tools such as our CI workflows and our test suite, which aid in the creation of stable, robust, and tested software.

After thinking about it, I decided to archive this package and use yours instead for now. 😅

**Comment by AngeloCore** [comment]
I forgot to ask, is everything right?
